export const siteConfig = {
  name: "Veltrix Labs",
  tagline: "Reliable engineering intelligence for production systems",
  description:
    "Veltrix Labs helps startups and businesses design, build, and scale secure software systems, automation workflows, cloud platforms, and operational tools.",
  url: "https://veltrixlabs.com",
  contactEmail: "hello@veltrixlabs.com",
  legalName: "Veltrix Labs",
  founderName: "Aakarshan Chadha",
  founderTitle: "Founder & Technical Consultant",
  locale: "en_GB",
  keywords: [
    "Veltrix Labs",
    "AI automation consultant Germany",
    "full-stack developer Germany",
    "SaaS engineering consultant",
    "cloud infrastructure consultant",
    "CRM dashboard developer",
    "Next.js developer Germany",
    "technical consultant Europe India",
    "custom software development",
    "production AI systems",
    "business automation systems",
    "engineering consultancy Germany",
    "production-grade software",
  ],
  socialLinks: {
    linkedin: "https://www.linkedin.com/company/veltrix-labs",
    github: "https://github.com/veltrix-labs",
  },
} as const;
