export const siteConfig = {
  name: "Logicform Solutions",
  tagline: "AI-First Software, Automation & Business Systems",
  description:
    "Logicform Solutions builds AI-first software systems, business automation workflows, dashboards, websites, cloud-ready platforms, and internal tools for small businesses, founders, and growing teams.",
  url: "https://logicformsolutions.com",
  contactEmail: "chadhaaakarshan@gmail.com",
  legalName: "Logicform Solutions",
  founderName: "Aakarshan Chadha",
  founderTitle: "Founder & Technical Consultant",
  locale: "en_GB",
  keywords: [
    "Logicform Solutions",
    "AI automation consultant Germany",
    "full-stack developer Germany",
    "SaaS engineering consultant",
    "cloud infrastructure consultant",
    "CRM dashboard developer",
    "Next.js developer Germany",
    "technical consultant Europe India",
    "custom software development",
    "production AI systems",
    "business automation systems",
    "engineering consultancy Germany",
    "production-grade software",
  ],
  socialLinks: {
    linkedin: "https://www.linkedin.com/company/logicform-solutions",
    github: "https://github.com/logicform-solutions",
  },
} as const;
